const { pool } = require("../dbConfig");

exports.queryKics = async function () {
    try {
        const connection = await pool.getConnection(async (conn) => conn);

        try{
        // SQL - 가용자본 :
        // AVAILABLE CAPITAL
        connection.query(
            `INSERT INTO available_capital 
            (SETL_YM, EXE_IDNO, PAP_NAV, DISAPP_CAPITAL, RECL_T2_CAPITAL
            , T1_CAPITAL,T2_CAPITAL, AVAILABLE_CAPITAL
            )

            VALUES
            (
			(SELECT SETL_YM FROM BASE_YM)
			,(SELECT EXE_IDNO FROM BASE_YM)  
            , (SELECT PAP_NAV
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            )
			, (SELECT DISAPP_CAPITAL
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            )
			, (SELECT SUGI1+SUGI2+REFUND_RSV_EXS+SUGI8+SUGI9
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            )
			, (SELECT PAP_NAV-DISAPP_CAPITAL+(SUGI1+SUGI2+REFUND_RSV_EXS+SUGI8+SUGI9)
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            )
			, (SELECT LEAST((SUGI1+SUGI2+REFUND_RSV_EXS+SUGI9+SUGI15+ADD_AVL_CAPITAL)
            ,0.5*(SELECT REQUIRED_CAPITAL FROM REQUIRED_CAPITAL
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)))+REFUND_RSV_EXS
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            )
            , (SELECT A.BASIC + B.SUPPLE
            FROM            
			(SELECT (PAP_NAV-DISAPP_CAPITAL+(SUGI1+SUGI2+REFUND_RSV_EXS+SUGI8+SUGI9)) AS BASIC
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            ) AS A
			, (SELECT (LEAST((SUGI1+SUGI2+REFUND_RSV_EXS+SUGI9+SUGI15+ADD_AVL_CAPITAL)
            ,0.5*(SELECT REQUIRED_CAPITAL FROM REQUIRED_CAPITAL
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)))+REFUND_RSV_EXS) AS SUPPLE
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
            ) AS B
            )
            ),
            
            (
			(SELECT SETL_YM FROM COMP_YM)
			,(SELECT EXE_IDNO FROM COMP_YM)  
            , (SELECT PAP_NAV
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            )
			, (SELECT DISAPP_CAPITAL
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            )
			, (SELECT SUGI1+SUGI2+REFUND_RSV_EXS+SUGI8+SUGI9
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            )
			, (SELECT PAP_NAV-DISAPP_CAPITAL+(SUGI1+SUGI2+REFUND_RSV_EXS+SUGI8+SUGI9)
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            )
			, (SELECT LEAST((SUGI1+SUGI2+REFUND_RSV_EXS+SUGI9+SUGI15+ADD_AVL_CAPITAL)
            ,0.5*(SELECT REQUIRED_CAPITAL FROM REQUIRED_CAPITAL
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)))+REFUND_RSV_EXS
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            )
            , (SELECT A.BASIC + B.SUPPLE
            FROM            
			(SELECT (PAP_NAV-DISAPP_CAPITAL+(SUGI1+SUGI2+REFUND_RSV_EXS+SUGI8+SUGI9)) AS BASIC
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            ) AS A
			, (SELECT (LEAST((SUGI1+SUGI2+REFUND_RSV_EXS+SUGI9+SUGI15+ADD_AVL_CAPITAL)
            ,0.5*(SELECT REQUIRED_CAPITAL FROM REQUIRED_CAPITAL
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)))+REFUND_RSV_EXS) AS SUPPLE
            FROM AVL_CALC
			WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
			AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
            ) AS B
            )
            );
            `                                
        );
               
        } catch (err) {
            console.error(" ##### Insert From DB Query Error ##### ");
            return false;
        }
    }catch (err) {
        console.error("##### DB Access Error #####");
        return false;
    }
}