const { pool } = require("../dbConfig");

exports.queryKics = async function () {
    try {
        const connection = await pool.getConnection(async (conn) => conn);

        try{
        // SQL - 금리위험액 :
        // INTEREST_RISK
        connection.query(
            `INSERT INTO INTEREST_RISK 
            (SETL_YM, EXE_IDNO, ITR_AVG_RISK,ITR_RISE_RISK, ITR_FALL_RISK
            , ITR_FLAT_RISK, ITR_ICLN_RISK
            )

            VALUES
            (
			(SELECT SETL_YM FROM BASE_YM)
			,(SELECT EXE_IDNO FROM BASE_YM)  
            , (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_AVG_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 111
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 111
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_RISE_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 112
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 112
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_FALL_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 113
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 113
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_FLAT_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 114
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 114
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_ICLN_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 115
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM BASE_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM BASE_YM)
				AND ITR_SHOCK_SCN = 115
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
            ),
            
              (
			(SELECT SETL_YM FROM COMP_YM)
			,(SELECT EXE_IDNO FROM COMP_YM)  
            , (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_AVG_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 111
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 111
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_RISE_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 112
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 112
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_FALL_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 113
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 113
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_FLAT_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 114
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 114
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
				
			, (SELECT GREATEST(A.NAV-B.NAV,0) AS ITR_ICLN_RISK FROM
				(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 100
				AND ASET_LIAB_CD = 2) AS B
				) AS A
				,(SELECT (A.A_FV - B.L_FV) AS NAV FROM
				(SELECT SUM(ITR_FV) AS A_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 115
				AND ASET_LIAB_CD = 1) AS A
				,(SELECT SUM(ITR_FV) AS L_FV FROM ITR_FV_DT
				WHERE SETL_YM = (SELECT SETL_YM FROM COMP_YM)
				AND EXE_IDNO = (SELECT EXE_IDNO FROM COMP_YM)
				AND ITR_SHOCK_SCN = 115
				AND ASET_LIAB_CD = 2) AS B
				) AS B
				)
            )
            ;
            `                                
        );
               
        } catch (err) {
            console.error(" ##### Insert From DB Query Error ##### ");
            return false;
        }
    }catch (err) {
        console.error("##### DB Access Error #####");
        return false;
    }
}